project:
  type: website
  resources: 
    - ads.txt

website:
  title: "Running on Numbers"
  favicon: favicon_io/favicon.ico
  google-analytics: "G-BJQPN133Q6"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/oliverc1623
      - icon: twitter
        href: https://x.com/runnerdude97
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



