project:
  type: website

website:
  title: "Running on Numbers"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/oliverc1623
      - icon: twitter
        href: https://x.com/runnerdude97
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



